### ISSUE TITLE
Feature Request: Go to user profile function

### ISSUE THREAD

**Issue by sometimesok** [Lanny/ISS#77]
In the members page there should be a go to user via search function.
The username should populate as the user spells it out.

At the moment if a user want to visit another user's profile, the user would need to navigate the threads and post and hope they find the profile they are looking for.
The search page requires a query.

... For some reason I am getting stuck in trying to add the feature ...

**Comment by Lanny** [comment]
Added in 9a1db24c26f96d324e110f5a9434997bbcdd932b
