### ISSUE TITLE
Issue: Thanks button disappears after thanking

### ISSUE THREAD

**Issue by sometimesok** [Lanny/ISS#87]
Unthank button appears after refreshing the page.

**Comment by Lanny** [comment]
Good catch, did some optimizations on thread rendering a couple weeks ago and I think that was the cause since there's a different code-path to render the unthank button after clicking. Will look into it.

**Comment by Lanny** [comment]
Fixed as of ab45bba7828c5e3af62b7d872d088fac5cb5c539
