### ISSUE TITLE
Users who utilize the 'Report' feature should have their profile automatically branded as a "Known Rattox"

### ISSUE THREAD

**Issue by LannysRealMom** [Lanny/ISS#89]
Their avatar shall be changed to an image of a rat, and be made unchangeable for a short period of time.  Their user title should be modified with the permanent addition of a prefix identifying them as a rat, examples: [KNOWN RATTOX] , [CONFIRMED TATTLER] , or the rat emoji: 🐀.

**Comment by Lanny** [comment]
reported for filing a fake feature suggestion
