### ISSUE TITLE
Issue: Forums do not list in the search page

### ISSUE THREAD

**Issue by sometimesok** [Lanny/ISS#90]
I see 'Forum object (x)' where x is a number in the search page where you should be able to specify which forum to search in.

**Comment by Lanny** [comment]
yup, fallout from the py3 migration, __unicode__ methods are now not a thing. Thanks for the report, I'm working on it.

**Comment by Lanny** [comment]
Fixed in 35610b5a0ff102a2d2236ff2f7e125cd5772d908
